name: robotlegs
version: 0.1.4
author: Hans Van den Keybus
description: Robotlegs for Google Dart
dependencies:
  browser: any
  dotdotcommadot_messaging:
    path: C:\Users\hvk\DartWorkspace\dotdotcommadot_messaging
  polymer: any
  robotlegs_di:
    path: C:\Users\hvk\DartWorkspace\robotlegs_di
